import { readFileSync } from 'node:fs';
import * as path from 'node:path/posix';
import { TypeGenerator } from 'json2jsii';
import type { FileBaseOptions, IResolver, Project, Task } from 'projen';
import { Component, JsonPatch, TextFile, javascript } from 'projen';

/**
 * The name of the task (managed by `UpgradeDependencies`, see
 * `setupUpgradeDependencies`) whose workflow the `update-schemas` task is
 * wired into.
 */
const UPGRADE_BUNDLED_TASK = 'upgrade-bundled';

const SCRIPT_PATH = path.join('scripts', 'update-schema.js');

export interface JsiiFromJsonSchemaProps extends FileBaseOptions {
  /**
   * The name of the JSII struct (TypeScript interface) that is created.
   */
  readonly structName: string;
  /**
   * The source of the json schema.
   *
   * Can either be:
   * - A local file path. The file is read as-is at synth time.
   * - An `http(s)://` URL. The schema is vendored into `schemas/` (the file
   *   name is derived from the URL) and loaded from there at synth time.
   *   A step is added to the shared `update-schemas` task that re-downloads
   *   the file, so the vendored copy can be kept up to date automatically.
   */
  readonly schemaPath: string;
  /**
   * The path to the generated file.
   */
  readonly filePath: string;

  /**
   * The path to the generated file.
   */
  readonly transform?: (schema: any) => any;
}

/**
 * A component that generates a jsii compatible typescript file
 * from a json schema using json2jsii.
 */
export class JsiiFromJsonSchema extends TextFile {
  private readonly generator: TypeGenerator;

  constructor(project: Project, props: JsiiFromJsonSchemaProps) {
    super(project, props.filePath, {
      committed: true,
      marker: true,
      readonly: true,
    });

    const isUrl = /^https?:\/\//.test(props.schemaPath);

    // For URL sources, the schema is vendored into schemas/ and loaded from
    // there at synth time. A step is added to the shared update-schemas task
    // to periodically refresh the vendored copy from the source URL.
    const localSchemaPath = isUrl
      ? path.join('schemas', path.basename(props.schemaPath))
      : props.schemaPath;

    if (isUrl) {
      const updateSchemas = UpdateSchemasTask.getOrCreate(project);
      updateSchemas.addSchema(props.schemaPath, localSchemaPath);
    }

    // Load and parse the JSON schema file
    const schemaContent = readFileSync(localSchemaPath, 'utf-8');
    const schema = JSON.parse(schemaContent);
    const transform = props.transform ?? ((s) => s);

    this.generator = TypeGenerator.forStruct(
      props.structName,
      transform(schema),
      {
        toJson: true,
        toJsonInternal: true,
        transformations: {
          convertConstToEnum: true,
          hoistSingletonUnions: true,
          convertNullUnionsToOptional: true,
          simplifyElementArrayUnions: true,
        },
      },
    );

    javascript.Eslint.of(project)?.addIgnorePattern(this.path);
    javascript.Jest.of(project)?.addIgnorePattern(this.path);
  }

  protected synthesizeContent(_: IResolver): string | undefined {
    return [
      ...(this.marker ? [`// ${this.marker}`] : []),
      renameProhibitedMembers(this.generator.render()),
    ].join('\n');
  }
}

// json2jsii appends a trailing "_" to properties named "build", "equals" or
// "hashcode" (reserved struct method names across jsii target languages), but
// that trailing underscore itself violates jsii's camelCase naming rule. Fix
// up the generated TypeScript identifiers; the schema/TOML key (e.g. the
// quoted 'build' in the generated toJson function) is left untouched.
const PROHIBITED_MEMBER_RENAMES: Record<string, string> = {
  build_: 'buildValue',
  equals_: 'equalsValue',
  hashcode_: 'hashcodeValue',
};

export function renameProhibitedMembers(code: string): string {
  return Object.entries(PROHIBITED_MEMBER_RENAMES).reduce(
    (result, [from, to]) => result.replace(new RegExp(`\\b${from}\\b`, 'g'), to),
    code,
  );
}

/**
 * A singleton component that owns the `update-schemas` task, which
 * re-downloads all URL-sourced schemas into `schemas/`. It also wires that
 * task into the `upgrade-bundled` workflow (generated by
 * `UpgradeDependencies`), during `preSynthesize`, via a `JsonPatch`. This
 * can't be done by adding a step to the `upgrade-bundled` task itself,
 * since `UpgradeDependencies` locks that task for changes once constructed.
 *
 * At most one instance may exist per project; use `getOrCreate()` rather
 * than the constructor directly.
 */
class UpdateSchemasTask extends Component {
  public static readonly TASK_NAME = 'update-schemas';

  public static of(project: Project): UpdateSchemasTask | undefined {
    const isSelf = (c: Component): c is UpdateSchemasTask =>
      c instanceof UpdateSchemasTask;
    return project.components.find(isSelf);
  }

  /**
   * Returns the singleton `UpdateSchemasTask` for the project, creating it
   * if it doesn't exist yet.
   */
  public static getOrCreate(project: Project): UpdateSchemasTask {
    return (
      UpdateSchemasTask.of(project) ??
      new UpdateSchemasTask(project, UpdateSchemasTask.name)
    );
  }

  /**
   * The task that re-downloads all URL-sourced schemas into `schemas/`.
   */
  public readonly task: Task;

  private constructor(project: Project, id: string) {
    super(project, id);

    this.task = project.tasks.addTask(UpdateSchemasTask.TASK_NAME, {
      description: 'Updates vendored JSON schemas from their source URL',
    });
  }

  /**
   * Adds a step that re-downloads the schema at `url` into `localPath`.
   */
  public addSchema(url: string, localPath: string) {
    this.task.exec(`node ${SCRIPT_PATH} ${url} ${localPath}`, {
      name: `update schema: ${localPath}`,
    });
  }

  public preSynthesize() {
    const project = this.project;
    const upgradeBundled = project.components.find(
      (c): c is javascript.UpgradeDependencies =>
        c instanceof javascript.UpgradeDependencies &&
        c.upgradeTask.name === UPGRADE_BUNDLED_TASK,
    );

    for (const workflow of upgradeBundled?.workflows ?? []) {
      const upgradeJob = workflow.getJob('upgrade') as any;
      if (!upgradeJob || !workflow.file) {
        continue;
      }

      const insertAt =
        upgradeJob.steps.findIndex(
          (step: any) => step.name === 'Upgrade dependencies',
        ) + 1;

      workflow.file.patch(
        JsonPatch.add(`/jobs/upgrade/steps/${insertAt}`, {
          name: 'Update vendored schemas',
          run: `node ./projen.js ${UpdateSchemasTask.TASK_NAME}`,
        }),
      );
    }
  }
}

// The mise schema uses a literal "_" property key (e.g. `env._`, `vars._`, and
// the config root) for advanced/undocumented catch-all sections. json2jsii
// carries that name straight into the generated TypeScript (member name "_"
// and, for the nested object, a type name built from it, e.g. "Env_"), which
// jsii rejects (members can't start with "_" unless `@internal`, and type
// names must be PascalCased). Drop these properties from the schema so the
// generated struct stays jsii-compatible; the underlying `TomlFile` object
// remains mutable directly (e.g. via `addOverride`) for anyone who needs them.
export function stripUnderscoreProperties(node: any): any {
  if (Array.isArray(node)) {
    return node.map(stripUnderscoreProperties);
  }
  if (node && typeof node === 'object') {
    const result: any = {};
    for (const [key, value] of Object.entries(node)) {
      if (key === 'properties' && value && typeof value === 'object') {
        const { _, ...rest } = value as Record<string, any>;
        result[key] = stripUnderscoreProperties(rest);
        continue;
      }
      result[key] = stripUnderscoreProperties(value);
    }
    return result;
  }
  return node;
}

// json2jsii generates a `fromNumber` factory per anyOf branch, so sibling
// "integer"/"number" branches (both map to TS `number`) cause a duplicate
// function implementation. Collapse them into a single "number" branch.
export function dedupeAnyOfNumberTypes(node: any): any {
  if (Array.isArray(node)) {
    return node.map(dedupeAnyOfNumberTypes);
  }
  if (node && typeof node === 'object') {
    const result: any = {};
    for (const [key, value] of Object.entries(node)) {
      result[key] = dedupeAnyOfNumberTypes(value);
    }
    if (Array.isArray(result.anyOf)) {
      const seenTypes = new Set<string>();
      result.anyOf = result.anyOf.filter((entry: any) => {
        if (entry && typeof entry === 'object' && typeof entry.type === 'string' && Object.keys(entry).length === 1) {
          const normalizedType = entry.type === 'integer' ? 'number' : entry.type;
          if (seenTypes.has(normalizedType)) {
            return false;
          }
          seenTypes.add(normalizedType);
        }
        return true;
      });
    }
    return result;
  }
  return node;
}
